# python web env base
#
# VERSION 0.0.2

FROM python:2.7.15-stretch
MAINTAINER timeblink <timeblink@icloud.com>

# Install packages
ENV DEBIAN_FRONTEND noninteractive
RUN pip install --upgrade \
 pip \
 tornado \
 better_exceptions \
 PyYAML lxml \
 xlrd xlwt \
 requests \
 selenium \
 pymongo \
 Flask \

#ENV BETTER_EXCEPTIONS 1
