# gerrit
#
# VERSION 0.0.2

FROM centos/base:7
MAINTAINER work <work@work>

# Install packages
RUN rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND noninteractive
#RUN apt-get -y dist-upgrade && apt-get update && apt-get -y upgrade
#RUN apt-get update
RUN yum -y install epel-release
#RUN apt-get -y -m install luatex texlive-base texlive-luatex context gregoriotex pandoc
RUN yum -y install luatex texlive-base texlive-luatex context gregoriotex pandoc
#RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /var/lib/apt-/lists/*
