# FMSv2
# VERSION 0.0.2

FROM python/devops:2.7
MAINTAINER timeblink <timeblink@icloud.com>

VOLUME ["/website"]
WORKDIR /website
#CMD ["python","web.py"]
#ENTRYPOINT ["python","web.py"]
ENTRYPOINT ["python"]
