version: '3'

services:
  spark-master:
    image: bde2020/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    networks:
      - spark_nw
  spark-worker1:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker1
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker"
    networks:
      - spark_nw
  spark-worker2:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker2
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker"
    networks:
      - spark_nw
networks:
  spark_nw:
    #driver: bridge
    external: true
