version: '2.0'
services:
  sptools:
    image: python/sptools:2.7
    volumes:
      - /home/lutx0528/fullstack/develop/github/DockerMe/project/sp:/workspace
    depends_on:
      - chrome
    links:
      - chrome
    command: ["test2.py"]
  chrome:
    image: selenium/node-chrome:3.10.0-argon
    shm_size: '2gb'
    volumes:
      - /dev/shm:/dev/shm
      - /home/lutx0528/fullstack/develop/github/DockerMe/project/sp:/downloads:rw
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  hub:
    image: selenium/hub:3.10.0-argon
    ports:
      - "4444:4444"

