version: '3.0'

services:
  hub:
    image: selenium/hub:3.10.0-argon
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.10.0-argon
    shm_size: '2gb'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
  weblogin:
    image: debug/python:2.7
    volumes:
      - /home/lutx0528/fullstack/develop/github/DockerMe/runtime/sp:/workspace
    depends_on:
      - chrome
    links:
      - chrome
    working_dir: /workspace
    command: ["python","test.py"]

